INSERT INTO Etudiant(ID, CNE, FULLNAME, SEXE, AGE)
VALUES (NULL, "BH1", "SALAHEDDINE", "HOMME", 22);
INSERT INTO Etudiant(ID, CNE, FULLNAME, SEXE, AGE)
VALUES (NULL, "BH2", "AMINATA", "FEMME", 20);
INSERT INTO Etudiant(ID, CNE, FULLNAME, SEXE, AGE)
VALUES (NULL, "BH3", "RABIAA", "FEMME", 18);
INSERT INTO Etudiant(ID, CNE, FULLNAME, SEXE, AGE)
VALUES (NULL, "BH4", "SOUKAINA", "FEMME", 27);
INSERT INTO Etudiant(ID, CNE, FULLNAME, SEXE, AGE)
VALUES (NULL, "BH5", "ILIAS", "HOMME", 24);